// Ogma3/wwwroot/js/src-webcomponents/folder-tree.ts
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { Folders_GetFoldersOfClub as getClubFolders } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

type Folder = {
	id: number;
	parentFolderId: number | null;
	name: string;
	slug: string;
	canAdd: boolean;
};

type TreeItem = {
	id: number;
	name: string;
	canAdd: boolean;
	children: TreeItem[];
};

@customElement("o-folder-tree")
export class FolderTree extends LitElement {
	constructor() {
		super();
	}

	@property() clubId: number;
	@property() value: number | null = null;
	@property() current: number | null = null;
	@property() selected: number | null = this.value;
	@property() inputSelector?: string | undefined = undefined;

	@state() private folders: Folder[] = [];
	@state() private tree: TreeItem[] = [];
	@state() private name: string;
	@state() private input?: HTMLInputElement;

	async connectedCallback() {
		log.info("tree connected");
		super.connectedCallback();
		this.classList.add("wc-loaded");

		if (this.inputSelector !== undefined) {
			this.input = document.querySelector<HTMLInputElement>(this.inputSelector);
			this.input.value = null;
		}

		const response = await getClubFolders(this.clubId);
		if (response.ok) {
			this.folders = await response.json();
		} else {
			log.error(`Error fetching data: ${response.statusText}`);
		}

		this.#unflatten();
	}

	#select = (id: number) => {
		log.info(`Selecting folder with ID ${id} in the tree`);
		this.selected = id;
		this.input.value = `${id}`;
	};

	render() {
		return html`
			<div class="folder-tree active-border">
				${
					this.tree.length > 0
						? html` ${this.tree.map(this.#item)} `
						: html`<span>No folder found</span>`
				}
			</div>
		`;
	}

	#item = (folder: TreeItem) => {
		const tabindex = folder.id === this.current || !folder.canAdd ? "-1" : "0";

		const classes = classMap({
			disabled: folder.id === this.current,
			locked: !folder.canAdd,
		});

		return html`
			<div class="folder ${classes}">
				<span
					class="${this.selected === folder.id ? "active" : ""}"
					tabindex="${tabindex}"
					@click="${() => this.#select(folder.id)}"
				>
					${folder.name}
				</span>
				${folder.children?.map(this.#item) ?? ""}
			</div>
		`;
	};

	#unflatten = () => {
		const hashTable = Object.create(null);

		for (const aData of this.folders) {
			hashTable[aData.id] = { ...aData, children: [] };
		}

		for (const aData of this.folders) {
			if (aData.parentFolderId) {
				hashTable[aData.parentFolderId].children.push(hashTable[aData.id]);
			} else {
				this.tree.push(hashTable[aData.id]);
			}
		}
	};

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/src-solid/_folder-tree.tsx
import { GetApiFolders as getClubFolders } from "@g/paths-public";
import type { GetFolderResult } from "@g/types-public";
import { log } from "@h/logger";
import { customElement } from "solid-element";
import { For, Show, createSignal, onMount } from "solid-js";

type Folder = {
	id: number;
	name: string;
	slug: string;
	canAdd: boolean;
};

type TreeItem = Folder & {
	children: TreeItem[];
};

customElement(
	"o-folder-tree",
	{
		clubId: Number,
		value: {
			type: Number,
			default: null,
		},
		current: {
			type: Number,
			default: null,
		},
		selected: {
			type: Number,
			default: null,
		},
		inputSelector: String,
	},
	(props) => {
		const [folders, setFolders] = createSignal<GetFolderResult[]>([]);
		const [tree, setTree] = createSignal<TreeItem[]>([]);
		const [selected, setSelected] = createSignal(props.selected || props.value);
		const [input, setInput] = createSignal<HTMLInputElement>(null);

		onMount(async () => {
			log.info("tree connected");
			props.element.classList.add("wc-loaded");

			if (props.inputSelector !== undefined) {
				const inputElement = document.querySelector<HTMLInputElement>(props.inputSelector);
				setInput(inputElement);
				if (inputElement) {
					inputElement.value = null;
				}
			}

			const response = await getClubFolders(props.clubId);
			if (response.ok) {
				setFolders(response.data);
				unflatten();
			} else {
				log.error(`Error fetching data: ${response.statusText}`);
			}
		});

		const select = (id: number) => {
			log.info(`Selecting folder with ID ${id} in the tree`);
			setSelected(id);
			if (input()) {
				input().value = `${id}`;
			}
		};

		const unflatten = () => {
			const hashTable: { [id: number]: TreeItem } = {};
			const result: TreeItem[] = [];

			// First create all items
			for (const aData of folders()) {
				hashTable[aData.id] = { ...aData, children: [] };
			}

			// Then establish parent-child relationships
			for (const aData of folders()) {
				if (aData.parentFolderId) {
					hashTable[aData.parentFolderId].children.push(hashTable[aData.id]);
				} else {
					result.push(hashTable[aData.id]);
				}
			}

			setTree(result);
		};

		const renderItem = (folder: TreeItem) => {
			const tabindex = folder.id === props.current || !folder.canAdd ? "-1" : "0";
			const isDisabled = folder.id === props.current;
			const isLocked = !folder.canAdd;

			return (
				<div class={`folder ${isDisabled ? "disabled" : ""} ${isLocked ? "locked" : ""}`}>
					<span
						class={selected() === folder.id ? "active" : ""}
						tabindex={tabindex}
						onClick={() => select(folder.id)}
					>
						{folder.name}
					</span>
					<For each={folder.children}>{(child) => renderItem(child)}</For>
				</div>
			);
		};

		return () => (
			<div class="folder-tree active-border">
				<Show when={tree().length > 0} fallback={<span>No folder found</span>}>
					<For each={tree()}>{(folder) => renderItem(folder)}</For>
				</Show>
			</div>
		);
	},
);
