// Ogma3/wwwroot/js/src-webcomponents/block-user.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { PostApiUsersBlock as blockUser, DeleteApiUsersBlock as unblockUser } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

@customElement("o-block")
export class BlockUser extends LitElement {
	@property() userName: string;
	@property() csrf: string;
	@property() isBlocked: boolean;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		this.addEventListener("click", this.block);
		this.addEventListener("keydown", (e: KeyboardEvent) => {
			if (e.key === " ") {
				this.block();
				e.preventDefault();
			}
		});
	}

	render() {
		return html`<span> ${this.isBlocked ? "Unblock" : "Block"} </span>`;
	}

	private async block() {
		const send = this.isBlocked ? unblockUser : blockUser;

		const res = await send(
			{
				name: this.userName,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);

		if (res.ok) {
			this.isBlocked = res.data;
		} else {
			log.warn(res.statusText);
		}
	}

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/src-solid/block-user.tsx
import { PostApiUsersBlock as blockUser, DeleteApiUsersBlock as unblockUser } from "@g/paths-public";
import { log } from "@h/logger";
import { customElement } from "solid-element";
import { type Component, createSignal } from "solid-js";
import css from "./block-user.css";
import { Styled } from "./common/_styled";

const BlockUser: Component<{ userName: string; csrf: string; isBlocked: boolean }> = (props) => {
	// noShadowDOM();

	const [isBlocked, setIsBlocked] = createSignal(props.isBlocked);

	const block = async () => {
		const send = isBlocked() ? unblockUser : blockUser;

		const res = await send(
			{
				name: props.userName,
			},
			{
				RequestVerificationToken: props.csrf,
			},
		);

		if (res.ok) {
			setIsBlocked(res.data);
		} else {
			log.warn(res.statusText);
		}
	};

	return (
		<button class="block-btn" type="button" onClick={block}>
			{isBlocked() ? "Unblock" : "Block"}
		</button>
	);
};

customElement(
	"o-block",
	{
		userName: "",
		csrf: "",
		isBlocked: false,
	},
	Styled(BlockUser, css),
);
