// Ogma3/FrontendCode/typescript/src-webcomponents/chapter-read.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("o-read")
class ChapterRead extends LitElement {
	@property() accessor route: string;
	@property() accessor chapterId: number;

	connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
	}

	render() {
		return html`
			<button class="read-status" aria-label="Chapter read status" data-id="@c.Id">
				<o-icon icon="lucide:eye-off"></o-icon>
			</button>
		`;
	}
}

// Ogma3/FrontendCode/typescript/src-solid/chapter-read.tsx
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { onMount } from "solid-js";

const ChapterRead: ComponentType<{ route: string; chapterId: number }> = (props, { element }) => {
	noShadowDOM();

	onMount(() => {
		element.classList.add("wc-loaded");
	});

	return (
		<button type="button" class="read-status" aria-label="Chapter read status" data-id="@c.Id">
			<o-icon icon="lucide:eye-off" />
		</button>
	);
};

customElement(
	"o-read",
	{
		route: "",
		chapterId: 0,
	},
	ChapterRead,
);
