// Ogma3/FrontendCode/typescript/src-solid/clock.tsx
import { addToDate } from "@h/date-helpers";
import { addStyle } from "@h/jsx-wc-style";
import { EU, iso8601 } from "@h/tinytime-templates";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { createSignal, onCleanup, onMount } from "solid-js";
import { minifyCss } from "@h/minify.macro" with { type: "macro" };

const Clock: ComponentType<{ date: string }> = (props, { element }) => {
	noShadowDOM();
	const [date, setDate] = createSignal(new Date(props.date));

	onMount(() => {
		element.classList.add("wc-loaded");
		addStyle(
			element,
			minifyCss(`
				.time {
					font-family: "Courier New", Courier, monospace;
					letter-spacing: -2px;
					margin: auto 0;
				}
			`),
		);

		// Set up the timer
		const interval = setInterval(() => {
			setDate(addToDate(date(), { seconds: 1 }));
		}, 1000);

		onCleanup(() => clearInterval(interval));
	});

	return (
		<time class="timer" datetime={iso8601.render(date())} title="Server time">
			{EU.render(date())}
		</time>
	);
};

customElement(
	"o-clock",
	{
		date: "",
	},
	Clock,
);

// Ogma3/FrontendCode/typescript/svelte-webcomponents/Clock.svelte
<svelte:options customElement="my-element" />

<script lang="ts">
	import { onMount } from 'svelte';
	// Assuming these helpers are available in your project
	import { addToDate } from '../src-helpers/date-helpers';
	import { EU, iso8601 } from '../src-helpers/tinytime-templates';

	let { date: initialDate }: { date: Date } = $props();

	// Use $state for reactive date
	let date = $state(initialDate);

	// Use $derived for computed values
	let formattedDate = $derived(EU.render(date));
	let isoDate = $derived(iso8601.render(date));

	onMount(() => {
		const intervalId = setInterval(() => {
			date = addToDate(date, { seconds: 1 });
		}, 1000);

		// Cleanup interval on component destroy
		return () => {
			clearInterval(intervalId);
		};
	});
</script>

<time class="timer" datetime={isoDate} title="Server time">
	{formattedDate}
</time>

<style>
	time {
		font-family: 'Courier New', Courier, monospace;
		letter-spacing: -2px;
		margin: auto 0;
	}
</style>
