// Ogma3/wwwroot/js/src-webcomponents/follow-button.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { PostApiUsersFollow as followUser, DeleteApiUsersFollow as unfollowUser } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

@customElement("o-follow")
export class FollowButton extends LitElement {
	@property() userName: string;
	@property() csrf: string;
	@property() isFollowed: boolean;

	connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
	}

	render() {
		return html`
			<button
				class="button max ${this.isFollowed ? "leave" : "join"}"
				title="${this.isFollowed ? "Unfollow" : "Follow"}"
				@click="${this.follow}"
			>
				${this.isFollowed ? "Following" : "Follow"}
			</button>
		`;
	}

	private async follow() {
		const send = this.isFollowed ? unfollowUser : followUser;

		const res = await send(
			{
				name: this.userName,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);
		if (res.ok) {
			this.isFollowed = res.data;
		} else {
			log.warn(res.statusText);
		}
	}

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/svelte-webcomponents/FollowButton.svelte
<svelte:options customElement="my-element" />

<script lang="ts">
import { log } from "../src-helpers/logger";
import { PostApiUsersFollow as followUser, DeleteApiUsersFollow as unfollowUser } from "../generated/paths-public";

const {
	userName,
	csrf,
	isFollowed: initialIsFollowed,
}: {
	userName: string;
	csrf: string;
	isFollowed: boolean;
} = $props();

// Reactive state for followed status and loading
let isFollowed = $state(initialIsFollowed);
let isLoading = $state(false);

// Derived state for button text and title
const buttonText = $derived(isFollowed ? "Following" : "Follow");
const buttonTitle = $derived(isFollowed ? "Unfollow" : "Follow");
const buttonClass = $derived(`button max ${isFollowed ? "leave" : "join"}`);

async function handleFollowToggle() {
	if (isLoading) return;
	isLoading = true;

	const action = isFollowed ? unfollowUser : followUser;

	try {
		const res = await action({ name: userName }, { RequestVerificationToken: csrf });

		if (res.ok) {
			isFollowed = res.data;
		} else {
			log.warn(`Failed to ${isFollowed ? "unfollow" : "follow"} user: ${res.statusText}`);
		}
	} catch (error) {
		log.error("Error during follow/unfollow action:", error);
	} finally {
		isLoading = false;
	}
}
</script>

<button
	class={buttonClass}
	title={buttonTitle}
	onclick={handleFollowToggle}
	disabled={isLoading}
>
	{buttonText}
	{#if isLoading}
		...
	{/if}
</button>

<style>
	/* Add styles for .button, .max, .leave, .join if needed */
	button {
		/* Example styles */
		padding: 8px 15px;
		cursor: pointer;
	}
	button:disabled {
		opacity: 0.7;
		cursor: wait;
	}
</style>
