// Ogma3/wwwroot/js/src-webcomponents/join-club-button.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { PostApiClubjoin as joinClub, DeleteApiClubjoin as leaveClub } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

@customElement("o-join")
export class JoinClubButton extends LitElement {
	@property() clubId: number;
	@property() csrf: string;
	@property() isMember = false;

	connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
	}

	render() {
		return html`
			<button
				class="button max ${this.isMember ? "leave" : "join"}"
				title="${this.isMember ? "Leave" : "Join"}"
				@click="${this.join}"
			>
				${this.isMember ? "Leave club" : "Join club"}
			</button>
		`;
	}

	private join = async () => {
		const send = this.isMember ? leaveClub : joinClub;

		const res = await send(
			{
				clubId: this.clubId,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);
		if (res.ok) {
			const data = res.data;
			this.isMember = data === true;
		} else {
			log.warn(res.statusText);
		}
	};

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/svelte-webcomponents/JoinClubButton.svelte
<svelte:options customElement="my-element" />

<script lang="ts">
import { log } from "../src-helpers/logger";
import { PostApiClubjoin as joinClub, DeleteApiClubjoin as leaveClub } from "../generated/paths-public";

const {
	clubId,
	csrf,
	isMember: initialIsMember,
}: {
	clubId: number;
	csrf: string;
	isMember: boolean;
} = $props();

// Reactive state
let isMember = $state(initialIsMember);
let isLoading = $state(false);

// Derived state
const buttonText = $derived(isMember ? "Leave club" : "Join club");
const buttonTitle = $derived(isMember ? "Leave" : "Join");
const buttonClass = $derived(`button max ${isMember ? "leave" : "join"}`);

async function handleJoinToggle() {
	if (isLoading) return;
	isLoading = true;

	const action = isMember ? leaveClub : joinClub;

	try {
		const res = await action({ clubId: clubId }, { RequestVerificationToken: csrf });

		if (res.ok) {
			isMember = res.data === true;
		} else {
			log.warn(`Failed to ${isMember ? "leave" : "join"} club: ${res.statusText}`);
		}
	} catch (error) {
		log.error("Error during join/leave action:", error);
	} finally {
		isLoading = false;
	}
}
</script>

<button
	class={buttonClass}
	title={buttonTitle}
	onclick={handleJoinToggle}
	disabled={isLoading}
>
	{buttonText}
	{#if isLoading}
		...
	{/if}
</button>

<style>
	/* Add styles for .button, .max, .leave, .join if needed */
	button {
		padding: 8px 15px;
		cursor: pointer;
	}
	button:disabled {
		opacity: 0.7;
		cursor: wait;
	}
</style>
