// Ogma3/FrontendCode/typescript/src/comp/block-user.tsx
import { PostApiUsersBlock as blockUser, DeleteApiUsersBlock as unblockUser } from "@g/paths-public";
import { log } from "@h/logger";
import { component } from "@h/web-components";
import IcRoundBlock from "icon:ic:round-block";
import type { Component } from "solid-js";
import css from "./block-user.css";

const BlockUser: Component<{ userName: string; csrf: string; isBlocked: boolean }> = (props) => {
	// noShadowDOM();

	let isBlocked = $signal(props.isBlocked);

	const block = async () => {
		const send = isBlocked ? unblockUser : blockUser;

		const res = await send(
			{
				name: props.userName,
			},
			{
				RequestVerificationToken: props.csrf,
			},
		);

		if (res.ok) {
			isBlocked = res.data;
		} else {
			log.warn(res.data ?? res.statusText);
		}
	};

	return (
		<button class="block-btn" type="button" onClick={block}>
			<IcRoundBlock />
			{isBlocked ? "Unblock" : "Block"}
		</button>
	);
};

component(
	"o-block",
	{
		userName: "",
		csrf: "",
		isBlocked: false,
	},
	BlockUser,
	css,
);

// Ogma3/FrontendCode/typescript/src-webcomponents/block-user.ts
import { PostApiUsersBlock as blockUser, DeleteApiUsersBlock as unblockUser } from "@g/paths-public";
import { log } from "@h/logger";
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("o-block")
export class BlockUser extends LitElement {
	@property() accessor userName: string;
	@property() accessor csrf: string;
	@property() accessor isBlocked: boolean;

	render() {
		return html`<button @click="${this.block}"> ${this.isBlocked ? "Unblock" : "Block"} </button>`;
	}

	private async block() {
		const send = this.isBlocked ? unblockUser : blockUser;

		const res = await send(
			{
				name: this.userName,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);

		if (res.ok) {
			this.isBlocked = res.data;
		} else {
			log.warn(res.statusText);
		}
	}

	createRenderRoot() {
		return this;
	}
}
