// Ogma3/FrontendCode/typescript/src/comp/featured-in-clubs.tsx
import { GetApiClubsStory as getFeaturingClubs } from "@g/paths-public";
import type { GetClubsWithStoryResult } from "@g/types-public";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { createResource, For, Show } from "solid-js";
import { Dialog, type DialogApi } from "./common/_dialog";

const id = "featured-in-clubs";
const tagOverflow = 7;

const Club = ({ club }: { club: GetClubsWithStoryResult }) => (
	<a
		href={`/club/${club.id}/${club.name.toLowerCase().replace(" ", "-")}`}
		target="_blank"
		class="club"
		rel="noreferrer"
	>
		<img src={club.icon ?? "ph-250.png"} alt={club.name} width="48" height="48" />
		<span>{club.name}</span>
		<For each={club.folders.slice(0, tagOverflow)}>{(f) => <span class="folder">{f}</span>}</For>
		<Show when={club.folders.length > tagOverflow}>
			<span class="overflow">+ {club.folders.length - tagOverflow} more</span>
		</Show>
	</a>
);

const FeaturedInClubs: ComponentType<{ storyId: number }> = (props) => {
	noShadowDOM();

	let isOpen = $signal(false);
	const [clubs] = createResource($get(isOpen), async (condition: boolean) => {
		if (!condition) return null;
		const res = await getFeaturingClubs(props.storyId);
		return res.ok ? res.data : null;
	});
	const dialogRef = $signal<DialogApi>();

	const open = () => {
		isOpen = true;
		dialogRef?.open();
	};

	return (
		<>
			<button type="button" aria-controls={id} class="club-wc-button" onClick={open}>
				Featured in clubs
			</button>

			<Dialog
				ref={$set(dialogRef)}
				classes={["club-folder-selector"]}
				contentClass="clubs"
				header={<span>Featured in</span>}
			>
				<For each={clubs()} fallback={<div>This story hasn't been added to any clubs yet.</div>}>
					{(c) => <Club club={c} />}
				</For>
			</Dialog>
		</>
	);
};

customElement(
	"o-featured-in-clubs",
	{
		storyId: 0,
	},
	FeaturedInClubs,
);

// Ogma3/FrontendCode/typescript/src-webcomponents/featured-in-clubs.ts
import { GetApiClubsStory as getFeaturingClubs } from "@g/paths-public";
import type { GetClubsWithStoryResult } from "@g/types-public";
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { when } from "lit/directives/when.js";

@customElement("o-featured-in-clubs")
export class FeaturedInClubs extends LitElement {
	@property() accessor storyId: number;
	@state() private accessor visible: boolean;
	@state() private accessor clubs: GetClubsWithStoryResult[];

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		await this.fetch();
	}

	private async fetch() {
		const response = await getFeaturingClubs(this.storyId);
		if (response.ok) {
			this.clubs = response.data;
		}
	}

	private async open() {
		this.visible = true;
		await this.fetch();
	}

	private clubsView = () =>
		when(
			this.clubs.length > 0,
			() =>
				html`
					<div class="clubs">
						${map(
							this.clubs,
							(c) => html`
								<a href="/club/${c.id}/${c.name.toLowerCase().replace(" ", "-")}" target="_blank" class="club">
									<img src="${c.icon ?? "ph-250.png"}" alt="${c.name}" width="48" height="48" />
									<span>${c.name}</span>
									${map(c.folders.slice(0, 5), (f) => html`<span class="folder">${f}</span>`)}
									${when(c.folders.length > 5, () => html`<span class="overflow">+ ${c.folders.length - 5} more</span>`)}
								</a>
							`,
						)}
					</div>`,
			() => html`
				<div>This story hasn't been added to any clubs yet.</div>
			`,
		);

	render() {
		return html`
			<button class="club-wc-button" @click="${async () => await this.open()}">Featured in clubs</button>

			${when(
				this.visible,
				() => html`
					<div
						class="club-folder-selector my-modal"
						@click="${() => {
							this.visible = false;
						}}"
					>
						<div class="content" @click="${(e: Event) => e.stopPropagation()}">
							<div class="header">
								<span>Featured in</span>
							</div>

							${this.clubsView()}
						</div>
					</div>
				`,
			)}
		`;
	}

	createRenderRoot() {
		return this;
	}
}
