// Ogma3/FrontendCode/typescript/src/comp/follow-button.tsx
import { PostApiUsersFollow as followUser, DeleteApiUsersFollow as unfollowUser } from "@g/paths-public";
import { log } from "@h/logger";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { createSignal } from "solid-js";

const FollowButton: ComponentType<{ userName: string; csrf: string; isFollowed: boolean }> = (props) => {
	noShadowDOM();

	const [isFollowed, setIsFollowed] = createSignal(props.isFollowed);

	const follow = async () => {
		const send = isFollowed() ? unfollowUser : followUser;

		const res = await send(
			{
				name: props.userName,
			},
			{
				RequestVerificationToken: props.csrf,
			},
		);

		if (res.ok) {
			setIsFollowed(res.data);
		} else {
			log.warn(res.statusText);
		}
	};

	return (
		<button
			type="button"
			class={`button max ${isFollowed() ? "leave" : "join"}`}
			title={isFollowed() ? "Unfollow" : "Follow"}
			onClick={follow}
		>
			{isFollowed() ? "Following" : "Follow"}
		</button>
	);
};

customElement(
	"o-follow",
	{
		userName: "",
		csrf: "",
		isFollowed: false,
	},
	FollowButton,
);

// Ogma3/FrontendCode/typescript/src-webcomponents/follow-button.ts
import { PostApiUsersFollow as followUser, DeleteApiUsersFollow as unfollowUser } from "@g/paths-public";
import { log } from "@h/logger";
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("o-follow")
export class FollowButton extends LitElement {
	@property() accessor userName: string;
	@property() accessor csrf: string;
	@property() accessor isFollowed: boolean;

	connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
	}

	render() {
		return html`
			<button
				class="button max ${this.isFollowed ? "leave" : "join"}"
				title="${this.isFollowed ? "Unfollow" : "Follow"}"
				@click="${this.follow}"
			>
				${this.isFollowed ? "Following" : "Follow"}
			</button>
		`;
	}

	private async follow() {
		const send = this.isFollowed ? unfollowUser : followUser;

		const res = await send(
			{
				name: this.userName,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);
		if (res.ok) {
			this.isFollowed = res.data;
		} else {
			log.warn(res.statusText);
		}
	}

	createRenderRoot() {
		return this;
	}
}
