// Ogma3/FrontendCode/typescript/src-solid/notifications-button.tsx
import { GetApiNotificationsCount as countNotifications } from "@g/paths-public";
import { log } from "@h/logger";
import { type ComponentType, customElement } from "solid-element";
import { Show, createSignal, onMount } from "solid-js";
import css from "./notifications-button.css";
import { styled } from "@h/jsx-wc-style";

const NotificationsButton: ComponentType<null> = (_, { element }) => {
	const [notifications, setNotifications] = createSignal(0);

	onMount(async () => {
		element.classList.add("wc-loaded");

		const res = await countNotifications();
		if (res.ok) {
			setNotifications(res.data);
		} else {
			log.error(res.statusText);
		}
	});

	const count = () => (notifications() <= 99 ? notifications().toString() : "99+");

	const linkTitle = () => (notifications() > 0 ? `${notifications()} notifications` : "Notifications");

	return (
		<a class="nav-link light notifications-btn" href="/notifications" title={linkTitle()}>
			<o-icon class="material-icons-outlined" icon="lucide:bell" />
			<Show when={notifications() > 0}>
				<span>{count()}</span>
			</Show>
		</a>
	);
};

customElement("o-notifications-button", null, styled(css)(NotificationsButton));

// Ogma3/FrontendCode/typescript/src-webcomponents/notifications-button.ts
import { GetApiNotificationsCount as countNotifications } from "@g/paths-public";
import { log } from "@h/logger";
import { LitElement, html, nothing } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("o-notifications-button")
export class NotificationsButton extends LitElement {
	@state() accessor notifications: number;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");

		const res = await countNotifications();
		if (res.ok) {
			this.notifications = res.data;
		} else {
			log.error(res.statusText);
		}
	}

	private count = () => (this.notifications <= 99 ? this.notifications.toString() : "99+");

	private linkTitle = () => (this.notifications > 0 ? `${this.notifications} notifications` : "Notifications");

	render() {
		return html`
			<a class="nav-link light notifications-btn" href="/notifications" title="${this.linkTitle()}">
				<o-icon class="material-icons-outlined" icon="lucide:bell"></o-icon>
				${(this.notifications ?? -1) > 0 ? html`<span>${this.count()}</span>` : nothing}
			</a>
		`;
	}

	createRenderRoot() {
		return this;
	}
}
