// Ogma3/FrontendCode/typescript/src-solid/qr-code.tsx
import { parseDom } from "@h/dom";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { createSignal, onMount } from "solid-js";
import { type QrCodeGenerateSvgOptions, renderSVG } from "uqr";

type WidthOrHeight =
	| { width: null | undefined; height: number }
	| { width: number; height: null | undefined }
	| { width: number; height: number };

const QrCode: ComponentType<WidthOrHeight & { data: string } & QrCodeGenerateSvgOptions> = (props, { element }) => {
	noShadowDOM();

	const [svg, setSvg] = createSignal<string>("");

	onMount(() => {
		let svg = renderSVG(props.data, props);

		if (props.width || props.height) {
			const svgDom = parseDom(svg);
			svgDom.setAttribute("width", (props.width ?? props.height).toString());
			svgDom.setAttribute("height", (props.height ?? props.width).toString());
			svg = svgDom.outerHTML;
		}

		setSvg(svg);
	});

	return <div innerHTML={svg()} />;
};

customElement(
	"qr-code",
	{
		width: null,
		height: null,
		data: "",
		ecc: "M",
		pixelSize: 4,
	},
	QrCode,
);

// Ogma3/FrontendCode/typescript/src-webcomponents/qr-code.ts
import { parseDom } from "@h/dom";
import { LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { unsafeSVG } from "lit/directives/unsafe-svg.js";
import { type QrCodeGenerateSvgOptions, renderSVG } from "uqr";

const opts: QrCodeGenerateSvgOptions = {
	pixelSize: 4,
	ecc: "M",
};

@customElement("qr-code")
export class QrCode extends LitElement {
	@property({ attribute: true }) accessor width: number | undefined;
	@property({ attribute: true }) accessor height: number | undefined;

	render() {
		const svgs: string[] = [];
		for (const child of this.children) {
			let svg = renderSVG(child.textContent, opts);

			if (this.width || this.height) {
				const svgDom = parseDom(svg);
				svgDom.setAttribute("width", (this.width ?? this.height).toString());
				svgDom.setAttribute("height", (this.height ?? this.width).toString());
				svg = svgDom.outerHTML;
			}

			svgs.push(svg);
		}
		this.innerHTML = "";
		return svgs.map((e) => unsafeSVG(e));
	}
}
