// Ogma3/FrontendCode/typescript/src-solid/table-info.tsx
import { GetAdminApiTelemetryGetTableInfo } from "@g/paths-internal";
import { convert } from "convert";
import { type Component, createSignal, createResource, For } from "solid-js";
import { customElement } from "solid-element";
import { styled } from "@h/jsx-wc-style";
import { orderBy } from "es-toolkit";
import css from "./table-info.css";

const TableInfo: Component = () => {
	const [sortBy, setSortBy] = createSignal<"size" | "name">("size");
	const [sortOrder, setSortOrder] = createSignal<"asc" | "desc">("desc");

	const [tableInfo, { mutate: setTableInfo }] = createResource(async () => {
		const res = await GetAdminApiTelemetryGetTableInfo();
		if (!res.ok) {
			return;
		}

		const data = res.data;

		const elements = Object.entries(data).map(([k, v]) => ({
			name: k,
			size: Number.parseInt(v),
		}));

		return orderBy(elements, [sortBy()], [sortOrder()]);
	});

	const sort = (by: "size" | "name") => {
		setSortBy(by);
		setSortOrder((prev) => (prev === "desc" ? "asc" : "desc"));
		setTableInfo((prev) => orderBy(prev, [by], [sortOrder()]));
	};

	const formatBytes = (bytes: number, decimals = 2) => {
		return convert(bytes, "bytes").to("best").toString(decimals);
	};

	return (
		<table class="o-table">
			<thead>
				<tr>
					<th>
						<button type="button" class="sort" onClick={[sort, "name"]}>
							Table {sortBy() !== "name" ? "⯁" : sortOrder() === "asc" ? "⯆" : "⯅"}
						</button>
					</th>
					<th colSpan={2}>
						<button type="button" class="sort" onClick={[sort, "size"]}>
							Size {sortBy() !== "size" ? "⯁" : sortOrder() === "asc" ? "⯆" : "⯅"}
						</button>
					</th>
				</tr>
			</thead>
			<tbody>
				<For
					each={tableInfo()}
					fallback={
						<tr>
							<td colSpan={3}>Loading...</td>
						</tr>
					}
				>
					{(item) => (
						<tr>
							<td>{item.name}</td>
							<td>{item.size} B</td>
							<td>{formatBytes(item.size)}</td>
						</tr>
					)}
				</For>
			</tbody>
		</table>
	);
};

customElement("table-info", {}, styled(css)(TableInfo));

// Ogma3/FrontendCode/typescript/src/admin/lit-components/table-info.ts
import { GetAdminApiTelemetryGetTableInfo } from "@g/paths-internal";
import { convert } from "convert";
import { LitElement, css, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { when } from "lit/directives/when.js";

@customElement("table-info")
export class TableInfo extends LitElement {
	@state() private sortBy: "size" | "name" = "size";
	@state() private sortOrder: "asc" | "desc" = "asc";
	@state() private tableInfo: { name: string; size: number }[] = [];

	// language=CSS
	static styles = css`
			table {
				border-collapse: collapse;
				outline: 1px solid var(--foreground-50);
			}
			tr:hover {
				background-color: var(--accent-10);
			}
			td {
				border: 1px solid var(--foreground-25);
				padding: 0.5rem;
			}
			th {
				cursor: pointer;
				user-select: none;
			}
		`;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		await this._load();
	}

	render() {
		return html`
			<table class="o-table">
				<tr>
					<th @click="${() => this._sort("name")}">
						Table ${this.sortBy !== "name" ? "⯁" : this.sortOrder === "asc" ? "⯆" : "⯅"}
					</th>
					<th colspan="2" @click="${() => this._sort("size")}">
						Size ${this.sortBy !== "size" ? "⯁" : this.sortOrder === "asc" ? "⯆" : "⯅"}
					</th>
				</tr>
				${when(
					this.tableInfo,
					() =>
						map(
							this.tableInfo,
							(i) => html`
								<tr>
									<td>${i.name}</td>
									<td>${i.size} B</td>
									<td>${this._formatBytes(i.size)}</td>
								</tr>
							`,
						),
					() =>
						html`<tr>
							<td colspan="3">Loading...</td>
						</tr>`,
				)}
			</table>
		`;
	}

	private _load = async () => {
		const res = await GetAdminApiTelemetryGetTableInfo();
		if (!res.ok) return;
		const data = res.data;
		this.tableInfo = Object.entries(data).map(([k, v]) => ({
			name: k,
			size: Number.parseInt(v),
		}));
	};

	private _sort(by: "size" | "name") {
		this.sortBy = by;
		this.sortOrder = this.sortOrder === "desc" ? "asc" : "desc";
		if (by === "size") {
			this.tableInfo.sort((a, b) => (this.sortOrder === "desc" ? a.size - b.size : b.size - a.size));
		} else {
			this.tableInfo.sort((a, b) =>
				this.sortOrder === "desc" ? a.name.localeCompare(b.name) : b.name.localeCompare(a.name),
			);
		}
	}

	private _formatBytes(bytes: number, decimals = 2) {
		const num = convert(bytes, "bytes").to("best");
		return `${num.quantity.toFixed(Math.abs(decimals))} ${num.unit}`;
	}
}
