// Ogma3/FrontendCode/typescript/src-solid/featured-in-clubs.tsx
import { GetApiClubsStory as getFeaturingClubs } from "@g/paths-public";
import type { GetClubsWithStoryResult } from "@g/types-public";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { For, Show, createSignal, onMount } from "solid-js";

const FeaturedInClubs: ComponentType<{ storyId: number }> = (props, { element }) => {
	noShadowDOM();

	const [visible, setVisible] = createSignal(false);
	const [clubs, setClubs] = createSignal<GetClubsWithStoryResult[]>([]);

	onMount(async () => {
		element.classList.add("wc-loaded");
		await fetch();
	});

	const fetch = async () => {
		const response = await getFeaturingClubs(props.storyId);
		if (response.ok) {
			setClubs(response.data);
		}
	};

	const open = async () => {
		setVisible(true);
		await fetch();
	};

	const clubsView = () => (
		<Show when={clubs().length > 0} fallback={<div>This story hasn't been added to any clubs yet.</div>}>
			<div class="clubs">
				<For each={clubs()}>
					{(c) => (
						<a
							href={`/club/${c.id}/${c.name.toLowerCase().replace(" ", "-")}`}
							target="_blank"
							class="club"
							rel="noreferrer"
						>
							<img src={c.icon ?? "ph-250.png"} alt={c.name} width="48" height="48" />
							<span>{c.name}</span>
							<For each={c.folders.slice(0, 5)}>{(f) => <span class="folder">{f}</span>}</For>
							<Show when={c.folders.length > 5}>
								<span class="overflow">+ {c.folders.length - 5} more</span>
							</Show>
						</a>
					)}
				</For>
			</div>
		</Show>
	);

	return (
		<>
			<button type="button" class="club-wc-button" onClick={open}>
				Featured in clubs
			</button>

			<Show when={visible()}>
				<div class="club-folder-selector my-modal" onClick={() => setVisible(false)}>
					<div class="content" onClick={(e) => e.stopPropagation()}>
						<div class="header">
							<span>Featured in</span>
						</div>

						{clubsView()}
					</div>
				</div>
			</Show>
		</>
	);
};

customElement(
	"o-featured-in-clubs",
	{
		storyId: 0,
	},
	FeaturedInClubs,
);

// Ogma3/wwwroot/js/src-webcomponents/featured-in-clubs.ts
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { map } from "lit/directives/map.js";
import { when } from "lit/directives/when.js";
import { GetApiClubsStory as getFeaturingClubs } from "../generated/paths-public";
import type { GetClubsWithStoryResult } from "../generated/types-public";

@customElement("o-featured-in-clubs")
export class FeaturedInClubs extends LitElement {
	@property() storyId: number;
	@state() private visible: boolean;
	@state() private clubs: GetClubsWithStoryResult[];

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		await this.fetch();
	}

	private async fetch() {
		const response = await getFeaturingClubs(this.storyId);
		if (response.ok) {
			this.clubs = response.data;
		}
	}

	private async open() {
		this.visible = true;
		await this.fetch();
	}

	private clubsView = () =>
		when(
			this.clubs.length > 0,
			() =>
				html`
					<div class="clubs">
						${map(
							this.clubs,
							(c) => html`
								<a href="/club/${c.id}/${c.name.toLowerCase().replace(" ", "-")}" target="_blank" class="club">
									<img src="${c.icon ?? "ph-250.png"}" alt="${c.name}" width="48" height="48" />
									<span>${c.name}</span>
									${map(c.folders.slice(0, 5), (f) => html`<span class="folder">${f}</span>`)}
									${when(c.folders.length > 5, () => html`<span class="overflow">+ ${c.folders.length - 5} more</span>`)}
								</a>
							`,
						)}
					</div>`,
			() => html`
				<div>This story hasn't been added to any clubs yet.</div>
			`,
		);

	render() {
		return html`
			<button class="club-wc-button" @click="${async () => await this.open()}">Featured in clubs</button>

			${when(
				this.visible,
				() => html`
					<div
						class="club-folder-selector my-modal"
						@click="${() => {
							this.visible = false;
						}}"
					>
						<div class="content" @click="${(e: Event) => e.stopPropagation()}">
							<div class="header">
								<span>Featured in</span>
							</div>

							${this.clubsView()}
						</div>
					</div>
				`,
			)}
		`;
	}

	createRenderRoot() {
		return this;
	}
}
