// Ogma3/FrontendCode/typescript/svelte-webcomponents/NotificationsButton.svelte
<svelte:options customElement="my-element" />

<script lang="ts">
import { onMount } from "svelte";
import { log } from "../src-helpers/logger";
import { GetApiNotificationsCount as countNotifications } from "../generated/paths-public";
import Icon from "./Icon.svelte"; // Assuming Icon.svelte

// Reactive state for notification count
let notificationCount = $state<number | null>(null); // Use null for initial loading state
let isLoading = $state(true);

onMount(async () => {
	try {
		const res = await countNotifications();
		if (res.ok) {
			notificationCount = res.data;
		} else {
			log.error(`Failed to fetch notification count: ${res.statusText}`);
			notificationCount = 0; // Set to 0 on error? Or handle differently.
		}
	} catch (error) {
		log.error("Error fetching notification count:", error);
		notificationCount = 0; // Set to 0 on error?
	} finally {
		isLoading = false;
	}
});

// Derived state for display count and title
const displayCount = $derived(() => {
	if (notificationCount === null || notificationCount <= 0) {
		return null;
	}
	return notificationCount <= 99 ? notificationCount.toString() : "99+";
});

const linkTitle = $derived(() => {
	if (notificationCount === null || notificationCount <= 0) {
		return "Notifications";
	}
	return `${notificationCount} notification${notificationCount === 1 ? "" : "s"}`;
});
</script>

<a class="nav-link light notifications-btn" href="/notifications" title={linkTitle}>
	<Icon class="material-icons-outlined" icon="lucide:bell" />
	{#if !isLoading && displayCount !== null}
		<span>{displayCount}</span>
	{/if}
	{#if isLoading}
		<span>...</span>
	{/if}
</a>

<style>
	/* Add styles for .nav-link, .light, .notifications-btn span if needed */
	.notifications-btn {
		position: relative;
		display: inline-flex;
		align-items: center;
	}
	.notifications-btn span {
		position: absolute;
		top: -5px;
		right: -8px;
		background-color: red; /* Example */
		color: white;
		border-radius: 50%;
		padding: 2px 5px;
		font-size: 0.7rem;
		min-width: 16px;
		text-align: center;
		line-height: 1;
	}
	.notifications-btn :global(.o-icon) { /* Style nested component */
		/* Add styles if needed */
	}

</style>

// Ogma3/wwwroot/js/src-webcomponents/notifications-button.ts
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import { GetApiNotificationsCount as countNotifications } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

@customElement("o-notifications-button")
export class NotificationsButton extends LitElement {
	@state() notifications: number;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");

		const res = await countNotifications();
		if (res.ok) {
			this.notifications = res.data;
		} else {
			log.error(res.statusText);
		}
	}

	private count = () => (this.notifications <= 99 ? this.notifications.toString() : "99+");

	private linkTitle = () => (this.notifications > 0 ? `${this.notifications} notifications` : "Notifications");

	render() {
		return html`
			<a class="nav-link light notifications-btn" href="/notifications" title="${this.linkTitle()}">
				<o-icon class="material-icons-outlined" icon="lucide:bell"></o-icon>
				${(this.notifications ?? -1) > 0 ? html`<span>${this.count()}</span>` : null}
			</a>
		`;
	}

	createRenderRoot() {
		return this;
	}
}
