// Ogma3/FrontendCode/typescript/src-solid/quote-box.tsx
import { GetApiQuotesRandom as getQuote } from "@g/paths-public";
import type { QuoteDto } from "@g/types-public";
import { type ComponentType, customElement, noShadowDOM } from "solid-element";
import { Show, createResource, createSignal, onMount } from "solid-js";

const QuoteBox: ComponentType<null> = (_, { element }) => {
	noShadowDOM();

	onMount(() => {
		element.classList.add("wc-loaded");
	});

	const [canLoad, setCanLoad] = createSignal(true);

	const loadQuote = async () => {
		if (!canLoad()) {
			return JSON.parse(window.localStorage.getItem("quote")) as QuoteDto;
		}
		setCanLoad(false);

		const response = await getQuote();

		setTimeout(
			() => {
				setCanLoad(true);
			},
			Number.parseInt(response.headers.get("retry-after")) * 1000,
		);

		if (response.ok) {
			window.localStorage.setItem("quote", JSON.stringify(response.data));
			return response.data;
		}

		if (response.status === 429) {
			return JSON.parse(window.localStorage.getItem("quote")) as QuoteDto;
		}
	};

	const [quote, { refetch }] = createResource<QuoteDto>(() => loadQuote(), {});

	const spinnerIcon = () => (canLoad() ? "lucide:refresh-cw" : "lucide:clock");

	return () => (
		<div id="quote" class="quote active-border">
			<button type="button" class="refresh" onClick={refetch}>
				<o-icon icon={spinnerIcon()} class={`material-icons-outlined ${quote.loading ? "spin" : ""}`} />
			</button>
			<Show when={quote()} fallback={<span>Loading the quote...</span>}>
				<em class="body">{quote().body}</em>
				<span class="author">{quote().author}</span>
			</Show>
		</div>
	);
};

customElement("quote-box", null, QuoteBox);

// Ogma3/wwwroot/js/src-webcomponents/quote-box.ts
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import { when } from "lit/directives/when.js";
import { GetApiQuotesRandom as getQuote } from "../generated/paths-public";
import { log } from "../src-helpers/logger";

interface Quote {
	body: string;
	author: string;
}

@customElement("quote-box")
export class QuoteBox extends LitElement {
	@state() accessor _loading: boolean;
	@state() accessor _quote: Quote;
	@state() accessor _canReload = true;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		await this.load();
	}

	render() {
		return html`
			<div id="quote" class="quote active-border">
				<div class="refresh" @click="${this.load}">
					<o-icon icon="${this.#spinnerIcon()}" class="material-icons-outlined ${this.#spinnerClass()}"></o-icon>
				</div>
				${when(
					this._quote,
					() => html`
						<em class="body">${this._quote.body}</em>
						<span class="author">${this._quote.author}</span>
					`,
					() => html` <span>Loading the quote...</span> `,
				)}
			</div>
		`;
	}

	#spinnerClass = () => (this._loading ? "spin" : "");
	#spinnerIcon = () => (this._canReload ? "lucide:refresh-cw" : "lucide:clock");

	async load() {
		if (!this._canReload) return;

		const response = await getQuote();
		if (response.ok) {
			this._quote = response.data;
			window.localStorage.setItem("quote", JSON.stringify(this._quote));
		} else if (response.status === 429) {
			this._quote = JSON.parse(window.localStorage.getItem("quote"));
		} else {
			log.error(response.statusText);
		}

		this._canReload = false;
		setTimeout(
			() => {
				this._canReload = true;
			},
			Number.parseInt(response.headers.get("retry-after")) * 1000,
		);
	}

	createRenderRoot() {
		return this;
	}
}
