// Ogma3/FrontendCode/typescript/src-webcomponents/club-folder-selector.ts
import {
	PostApiFoldersAddStory as addStoryToFolder,
	GetApiFolders as getFolders,
	GetApiClubsUser as getUserClubs,
} from "@g/paths-public";
import type { GetFolderResult, GetJoinedClubsResponse } from "@g/types-public";
import { log } from "@h/logger";
import { Task } from "@lit/task";
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { map } from "lit/directives/map.js";
import { when } from "lit/directives/when.js";

@customElement("o-club-folder-selector")
export class ClubFolderSelector extends LitElement {
	@property() accessor storyId: number;
	@property() accessor csrf: string;

	@state() private accessor clubs: GetJoinedClubsResponse[] = [];
	@state() private accessor selectedClub: GetJoinedClubsResponse | null = null;
	@state() private accessor status: { message: string; success: boolean } = {
		message: "",
		success: false,
	};
	@state() private accessor visible = false;

	@state() private accessor selectedFolder: GetFolderResult | null = null;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");

		const response = await getUserClubs();
		if (response.ok) {
			this.clubs = response.data;
		} else {
			log.error(`Error fetching data: ${response.statusText}`);
		}
	}

	private _foldersTask = new Task(this, {
		task: async ([selectedClub], { signal }) => {
			if (!selectedClub) {
				throw new Error("Club not selected");
			}
			const res = await getFolders(selectedClub.id, null, { signal });
			if (!res.ok) {
				throw new Error(res.statusText);
			}
			return res.data;
		},
		args: () => [this.selectedClub],
	});

	private renderFolders = () =>
		this._foldersTask.render({
			pending: () => html`Loading folders...`,
			complete: (folders) =>
				map(
					folders,
					(folder) => html`
						 <button
							 class="folder ${classMap({
									locked: !folder.canAdd,
									active: this.selectedFolder?.id === folder.id,
								})}"
							 @click="${() => this.select(folder)}"
						 >
							 ${folder.name}
						 </button>
					 `,
				),
			error: (e) => html`Error: ${e}`,
		});

	private selectedClubView = () => {
		return html`
			<div class="header">
				<img src="${this.selectedClub.icon ?? "ph-250.png"}" alt="${this.selectedClub.name}" width="32" height="32" />
				<span>${this.selectedClub.name}</span>
			</div>

			<div class="msg ${this.status.success ? "success" : "error"}">${this.status.message}</div>

			<div class="folders">${this.renderFolders()}</div>

			<div class="buttons">
				<button class="active-border add" @click="${this.add}">Add</button>
				<button class="active-border cancel" @click="${() => this.setClub(null)}">Go back</button>
			</div>
		`;
	};

	private allClubsView = () => html`
		<div class="header">
			<span>Your clubs</span>
		</div>

		<div class="clubs">
			${map(
				this.clubs,
				(c) => html`
					<button class="club" @click="${() => this.setClub(c)}">
						<img src="${c.icon ?? "ph-250.png"}" alt="${c.name}" width="48" height="48" />
						<span>${c.name}</span>
					</button>
				`,
			)}
		</div>
	`;

	render() {
		return html`
			<button class="club-wc-button" @click="${() => this.setVisibility(true)}">Add to folder</button>
			${when(
				this.visible,
				() => html`
					<div class="club-folder-selector my-modal" @click="${() => this.setVisibility(false)}">
						<div class="content" @click="${(e: Event) => e.stopPropagation()}">
							${this.selectedClub !== null ? this.selectedClubView() : this.allClubsView()}
						</div>
					</div>
				`,
			)}
		`;
	}

	private select = (folder: GetFolderResult) => {
		log.info(`Selecting folder with ID ${folder.id}`);
		this.selectedFolder = folder;
	};

	private setClub = (club: GetJoinedClubsResponse | null) => {
		this.selectedClub = club;
	};

	private setVisibility = (visibility: boolean) => {
		this.visible = visibility;
	};

	private add = async () => {
		if (this.selectedFolder === null) {
			this.status = {
				message: "You must select a folder!",
				success: false,
			};
			return;
		}

		const response = await addStoryToFolder(
			{
				folderId: this.selectedFolder.id,
				storyId: this.storyId,
			},
			{
				RequestVerificationToken: this.csrf,
			},
		);

		if (response.ok) {
			this.status = {
				message: "Successfully added",
				success: true,
			};
		} else if (typeof response.data === "string") {
			this.status = {
				message: response.data.replaceAll('"', ""),
				success: false,
			};
		}
	};

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/src/comp/club-folder-selector.tsx
import { GetApiClubsUser as getUserClubs, GetApiFolders as getFolders, PostApiFoldersAddStory as addStoryToFolder } from "@g/paths-public";
import type { GetFolderResult, GetJoinedClubsResponse } from "@g/types-public";
import { component } from "@h/web-components";
import { type ComponentType, noShadowDOM } from "solid-element";
import { createResource, For, Match, Switch } from "solid-js";
import { Dialog, type DialogApi } from "./common/_dialog";

const ClubFolderSelector: ComponentType<{ storyId: number; csrf: string }> = (props) => {
	noShadowDOM();

	let isOpen = $signal(false);
	let selectedClub = $signal<GetJoinedClubsResponse | null>(null);
	let status = $signal({ message: "", success: false });
	let selectedFolder = $signal<GetFolderResult | null>(null);
	let dialogRef = $signal<DialogApi>();

	const [clubs] = createResource($get(isOpen), async (condition) => {
		if (!condition) return null;
		const res = await getUserClubs();
		return res.ok ? res.data : null;
	});

	const [folders] = createResource($get(selectedClub), async (club) => {
		if (!club) {
			throw new Error("Club not selected");
		}
		const res = await getFolders(club.id);
		if (!res.ok) {
			throw new Error(res.statusText);
		}
		return res.data;
	});

	const reset = () => {
		selectedClub = null;
		selectedFolder = null;
		status = { message: "", success: false };
	};

	const open = () => {
		isOpen = true;
		dialogRef?.open();
	};

	const setClub = (club: GetJoinedClubsResponse | null) => {
		selectedClub = club;
		selectedFolder = null;
	};

	const add = async () => {
		const folder = selectedFolder;

		if (!folder) {
			status = {
				message: "You must select a folder!",
				success: false,
			};
			return;
		}

		const response = await addStoryToFolder(
			{
				folderId: folder.id,
				storyId: props.storyId,
			},
			{
				RequestVerificationToken: props.csrf,
			},
		);

		if (!response.ok) {
			status = {
				message: response.error,
				success: false,
			};
			return;
		}

		if (typeof response.data === "string") {
			status = {
				message: response.data,
				success: false,
			};
			return;
		}

		status = {
			message: "Successfully added",
			success: true,
		};
	};

	const selectedClubView = () => (
		<>
			<div class={`msg ${status.success ? "success" : "error"}`}>{status.message}</div>

			<div class="folders">
				<Switch>
					<Match when={folders.loading}>
						<div>Loading folders...</div>
					</Match>
					<Match when={folders.error}>
						<div>Error fetching folders</div>
					</Match>
					<Match when={folders}>
						<For each={folders()} fallback={<div>This club has no folders</div>}>
							{(folder) => (
								<button
									type="button"
									classList={{
										locked: !folder.canAdd,
										active: selectedFolder?.id === folder.id,
									}}
									class="folder"
									onClick={() => (selectedFolder = folder)}
								>
									{folder.name}
								</button>
							)}
						</For>
					</Match>
				</Switch>
			</div>

			<div class="buttons">
				<button type="button" class="active-border add" onClick={add}>
					Add
				</button>
				<button type="button" class="active-border cancel" onClick={[setClub, null]}>
					Go back
				</button>
			</div>
		</>
	);

	const allClubsView = () => (
		<div class="clubs">
			<For each={clubs()} fallback={<div>You're not a member of any clubs</div>}>
				{(club) => (
					<button type="button" class="club" onClick={[setClub, club]}>
						<img src={club.icon ?? "ph-250.png"} alt={club.name} width="48" height="48" />
						<span>{club.name}</span>
					</button>
				)}
			</For>
		</div>
	);

	const selectedView = () => {
		const club = selectedClub;

		if (!club) {
			return {
				view: allClubsView,
				head: <span>Your clubs</span>,
			};
		}

		return {
			view: selectedClubView,
			head: (
				<>
					<img src={club.icon ?? "ph-250.png"} alt={club.name} width="32" height="32" />
					<span>{club.name}</span>
				</>
			),
		};
	};

	return (
		<>
			<button type="button" class="club-wc-button" onClick={open}>
				Add to folder
			</button>

			<Dialog ref={$set(dialogRef)} onClose={reset} header={selectedView().head} classes={["club-folder-selector"]}>
				<div class="content">{selectedView().view()}</div>
			</Dialog>
		</>
	);
};

component(
	"o-club-folder-selector",
	{
		storyId: 0,
		csrf: "",
	},
	ClubFolderSelector,
);
