// Ogma3/FrontendCode/typescript/src-webcomponents/notifications-button.ts
import { GetApiNotificationsCount as countNotifications } from "@g/paths-public";
import { log } from "@h/logger";
import { LitElement, html, nothing } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("o-notifications-button")
export class NotificationsButton extends LitElement {
	@state() accessor notifications: number;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");

		const res = await countNotifications();
		if (res.ok) {
			this.notifications = res.data;
		} else {
			log.error(res.statusText);
		}
	}

	private count = () => (this.notifications <= 99 ? this.notifications.toString() : "99+");

	private linkTitle = () => (this.notifications > 0 ? `${this.notifications} notifications` : "Notifications");

	render() {
		return html`
			<a class="nav-link light notifications-btn" href="/notifications" title="${this.linkTitle()}">
				<o-icon class="material-icons-outlined" icon="lucide:bell"></o-icon>
				${(this.notifications ?? -1) > 0 ? html`<span>${this.count()}</span>` : nothing}
			</a>
		`;
	}

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/src/comp/notifications-button.tsx
import { GetApiNotificationsCount as countNotifications } from "@g/paths-public";
import type { Empty } from "@t/utils";
import { type ComponentType, customElement } from "solid-element";
import { createResource, Show } from "solid-js";
import { Styled } from "./common/_styled";
import css from "./notifications-button.css";

const NotificationsButton: ComponentType<Empty> = (_) => {
	const [notifications] = createResource(
		async () => {
			const res = await countNotifications();
			return res.ok ? res.data : -1;
		},
		{ initialValue: 0 },
	);

	const count = () => (notifications() <= 99 ? notifications().toString() : "99+");

	const linkTitle = () => (notifications() > 0 ? `${notifications()} notifications` : "Notifications");

	return (
		<a class="nav-link light notifications-btn" href="/notifications" title={linkTitle()}>
			<o-icon class="material-icons-outlined" icon="lucide:bell" />
			<Show when={notifications() > 0}>
				<span>{count()}</span>
			</Show>
		</a>
	);
};

customElement("o-notifications-button", {}, Styled(NotificationsButton, css));
