// Ogma3/FrontendCode/typescript/src-webcomponents/qr-code.ts
import { parseDom } from "@h/dom";
import { LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { unsafeSVG } from "lit/directives/unsafe-svg.js";
import { type QrCodeGenerateSvgOptions, renderSVG } from "uqr";

const opts: QrCodeGenerateSvgOptions = {
	pixelSize: 4,
	ecc: "M",
};

@customElement("qr-code")
export class QrCode extends LitElement {
	@property({ attribute: true }) accessor width: number | undefined;
	@property({ attribute: true }) accessor height: number | undefined;

	render() {
		const svgs: string[] = [];
		for (const child of this.children) {
			let svg = renderSVG(child.textContent, opts);

			if (this.width || this.height) {
				const svgDom = parseDom(svg);
				svgDom.setAttribute("width", (this.width ?? this.height).toString());
				svgDom.setAttribute("height", (this.height ?? this.width).toString());
				svg = svgDom.outerHTML;
			}

			svgs.push(svg);
		}
		this.innerHTML = "";
		return svgs.map((e) => unsafeSVG(e));
	}
}

// Ogma3/FrontendCode/typescript/src/comp/qr-code.tsx
import { parseDom } from "@h/dom";
import { type ComponentType, customElement } from "solid-element";
import { onMount } from "solid-js";
import { type QrCodeGenerateSvgOptions, renderSVG } from "uqr";

type WidthOrHeight =
	| { width: number; height?: number }
	| { width?: number; height: number }
	| { width: number; height: number };

const QrCode: ComponentType<WidthOrHeight & { data: string } & QrCodeGenerateSvgOptions> = (props) => {
	let svg = $signal<string>("");

	const width = props.width ?? props.height ?? 0;
	const height = props.height ?? props.width ?? 0;

	onMount(() => {
		let newSvg = renderSVG(props.data, props);

		if (props.width || props.height) {
			const svgDom = parseDom(newSvg);
			svgDom.setAttribute("width", width.toString());
			svgDom.setAttribute("height", height.toString());
			newSvg = svgDom.outerHTML;
		}

		svg = newSvg;
	});

	return <div style={{ width: `${width}px`, height: `${height}px`, padding: "5px" }} innerHTML={svg} />;
};

customElement(
	"qr-code",
	{
		width: 100,
		height: undefined,
		data: "",
		ecc: "M",
		pixelSize: 4,
	},
	QrCode,
);
