// Ogma3/FrontendCode/typescript/src-webcomponents/quote-box.ts
import { GetApiQuotesRandom as getQuote } from "@g/paths-public";
import { log } from "@h/logger";
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { when } from "lit/directives/when.js";

interface Quote {
	body: string;
	author: string;
}

@customElement("quote-box")
export class QuoteBox extends LitElement {
	@state() accessor _loading: boolean;
	@state() accessor _quote: Quote;
	@state() accessor _canReload = true;

	async connectedCallback() {
		super.connectedCallback();
		this.classList.add("wc-loaded");
		await this.load();
	}

	render() {
		return html`
			<div id="quote" class="quote active-border">
				<div class="refresh" @click="${this.load}">
					<o-icon icon="${this.spinnerIcon()}" class="material-icons-outlined ${classMap({ spin: this._loading })}"></o-icon>
				</div>
				${when(
					this._quote,
					() => html`
						<em class="body">${this._quote.body}</em>
						<span class="author">${this._quote.author}</span>
					`,
					() => html`<span>Loading the quote...</span>`,
				)}
			</div>
		`;
	}
	private spinnerIcon = (): string => (this._canReload ? "lucide:refresh-cw" : "lucide:clock");

	async load() {
		if (!this._canReload) {
			return;
		}

		const response = await getQuote();
		if (response.ok) {
			this._quote = response.data;
			window.localStorage.setItem("quote", JSON.stringify(this._quote));
		} else if (response.status === 429) {
			this._quote = JSON.parse(window.localStorage.getItem("quote"));
		} else {
			log.error(response.statusText);
		}

		this._canReload = false;
		setTimeout(
			() => {
				this._canReload = true;
			},
			Number.parseInt(response.headers.get("retry-after")) * 1000,
		);
	}

	createRenderRoot() {
		return this;
	}
}

// Ogma3/FrontendCode/typescript/src/comp/quote-box.tsx
import { GetApiQuotesRandom as getQuote } from "@g/paths-public";
import type { QuoteDto } from "@g/types-public";
import { makePersisted } from "@h/persisted";
import { component } from "@h/web-components";
import type { Empty } from "@t/utils";
import LucideClock from "icon:lucide:clock";
import LucideRefreshCw from "icon:lucide:refresh-cw";
import type { ComponentType } from "solid-element";
import { createResource, createSignal, Show } from "solid-js";
import css from "./quote-box.css";

const QuoteBox: ComponentType<Empty> = (_) => {
	let canFetch = $signal(true);
	const [getQuoteFromStore, setQuoteInStore] = makePersisted(createSignal<QuoteDto | null>(null), {
		name: "quote",
		storage: localStorage,
	});

	const loadQuote = async () => {
		const stored = getQuoteFromStore();

		if (!canFetch) {
			if (stored) {
				return stored;
			}
			throw new Error("Rate limited with no fallback");
		}

		const response = await getQuote();

		if (response.ok) {
			setQuoteInStore(response.data);
			return response.data;
		}

		if (response.status === 429) {
			const nextFetchTime = Number.parseInt(response.headers.get("Retry-After") ?? "0", 10) * 1000;
			canFetch = false;
			window.setTimeout(() => {
				canFetch = true;
			}, nextFetchTime);
			if (stored) {
				return stored;
			}
			throw new Error("Rate limited with no fallback");
		}
		throw new Error(`Quote fetch error: ${response.statusText}`);
	};

	const [quote, { refetch }] = createResource<QuoteDto>(loadQuote);

	return () => (
		<div id="quote" class="quote active-border">
			<button type="button" class="refresh" onClick={refetch} title="Get new quote">
				{canFetch ? <LucideRefreshCw /> : <LucideClock />}
			</button>
			<Show when={quote()} fallback={<span>Loading the quote...</span>}>
				{(q) => (
					<>
						<em class="body">{q().body}</em>
						<span class="author">{q().author}</span>
					</>
				)}
			</Show>
		</div>
	);
};

component("quote-box", {}, QuoteBox, css);
